name: e2e test daily

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * 1-5" # At 03:00 on every day-of-week from Monday through Friday.

jobs:
  ubuntu:
    name: e2e test daily
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        distro:
          - ubuntu
          - fedora
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v22

      - name: Upate flake
        run: nix flake update

      - name: Update mkosi
        run: nix run nixpkgs#nix-update -- --version=branch=main --flake mkosi-nightly

      - name: Build mkosi-nightly
        run: nix build .#mkosi-nightly

      - uses: nicknovitski/nix-develop@v1.0.0
        with:
          arguments: ".#mkosi-${{ matrix.distro }}-nightly"

      - name: Print mkosi store path
        run: command -v mkosi

      - name: Check ${{ matrix.distro }} image reproducibility
        run: nix run .#diffimage ${{ matrix.distro }}

      - name: Upload binary artifacts A
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: "${{ matrix.distro }}-A"
          path: "build-a/*"

      - name: Upload binary artifacts B
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: "${{ matrix.distro }}-B"
          path: "build-b/*"
